
[project]
name = "am-okay"
version = "1.0.9"
description = "A portable command-line tool for copying and moving files and directories with progress indication."
authors = [
    {name = "Amadou Baldé", email = "baldeuniversel@protonmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
keywords = ["file", "transfer", "buffer", "COPY", "CUT"]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = [
    "tqdm (>=4.67.1,<5.0.0)",
    "python-magic (>=0.4.27,<0.5.0)",
    "pywin32 (>=311,<312) ; sys_platform == 'win32'",
    "python-magic-bin (>=0.4.14,<0.5.0) ; sys_platform == 'win32'"
]

[project.urls]
Homepage = "https://github.com/baldeuniversel/am-okay"
Repository = "https://github.com/baldeuniversel/am-okay"
Documentation = "https://github.com/baldeuniversel/am-okay#readme"

[tool.poetry]
packages = [{include = "am_okay", from = "src"}]

[project.scripts]
am-okay = "am_okay.cli:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.0.2,<10.0.0)",
    "pylint (>=4.0.4,<5.0.0)",
    "mypy (>=1.19.1,<2.0.0)",
    "types-tqdm (>=4.67.3.20260205,<5.0.0.0)"
]
